export { start4 as default };
declare function start4(element: any, cfg: any): {
    opts: any;
    redraw: any;
    game: {
        initial: any;
        moves: any;
        players: any;
        metadata: any;
        mainline: any[];
        nodeAt: (path: any) => any;
        dataAt: (path: any) => any;
        title: () => string;
        pathAtMainlinePly: (ply: any) => any;
        hasPlayerName: () => boolean;
    };
    translate: (key: any) => any;
    path: any;
    ground: any;
    div: any;
    flipped: boolean;
    pane: string;
    autoScrollRequested: boolean;
    curNode: () => any;
    curData: () => any;
    goTo: (to: any, focus?: boolean) => void;
    canGoTo: (to: any) => boolean;
    toPath: (path: any, focus?: boolean) => void;
    focus: () => any;
    toggleMenu: () => void;
    togglePgn: () => void;
    orientation: () => any;
    flip: () => void;
    cgState: () => {
        fen: any;
        orientation: any;
        check: any;
        lastMove: any;
        turnColor: any;
    };
    analysisUrl: () => any;
    practiceUrl: () => string;
    setGround: (cg: any) => void;
    redrawGround: () => any;
    withGround: (f: any) => any;
};
